name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_fonts: ^7.0.1
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  syncfusion_flutter_charts: ^32.1.23
  syncfusion_flutter_calendar: ^32.1.23
  animate_do: ^4.2.0
  loading_animation_widget: ^1.3.0
  iconsax: ^0.0.8
  slideable: ^0.0.2
  flutter_slidable: ^4.0.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner : ^2.10.5

flutter:
  uses-material-design: true
